name: ShellCheck
on:
  push:
    branches:
      - main  # Branch to run check
    paths:
      - '**.sh'  # Start only if .sh files 
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run ShellCheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} +
